### ISSUE TITLE
Can't import CRF layer

### ISSUE THREAD

**Issue by lminer** [farizrahman4u/keras-contrib#139]
Whenever I try to import the CRF class, I get the following error:

```python
Traceback (most recent call last):
  File "keras_test2.py", line 12, in <module>
    from keras_contrib.layers import CRF
  File "build/bdist.macosx-10.12-x86_64/egg/keras_contrib/__init__.py", line 13, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/keras_contrib/optimizers/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/keras_contrib/optimizers/ftml.py", line 8, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/keras_contrib/optimizers/ftml.py", line 34, in FTML
AttributeError: 'module' object has no attribute 'legacy_get_updates_support'
```

**Comment by lminer** [comment]
It looks like that wrapper is on master branch of keras but not yet on the keras 2

**Comment by yushuinanrong** [comment]
@lminer 
Hi, would you mind to explain a bit more of how to install dev version of keras 2?

**Comment by lminer** [comment]
1. pip uninstall current version of keras
2. git clone keras repo
3. cd keras
4. python setup.py install

**Comment by yushuinanrong** [comment]
@lminer 
Thanks a lot! It works.
