### ISSUE TITLE
Cannot import name image_dim_ordering

### ISSUE THREAD

**Issue by abhaikollara** [farizrahman4u/keras-contrib#38]
I get an error when trying to import keras-contrib
```python 
import keras_contrib
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhai/keras-contrib/keras_contrib/__init__.py", line 2, in <module>
    from . import backend
  File "/home/abhai/keras-contrib/keras_contrib/backend/__init__.py", line 14, in <module>
    from .tensorflow_backend import *
  File "/home/abhai/keras-contrib/keras_contrib/backend/tensorflow_backend.py", line 14, in <module>
    from keras.backend.common import floatx, _EPSILON, image_dim_ordering, reset_uids
ImportError: cannot import name image_dim_ordering
```

**Comment by abhaikollara** [comment]
My bad, was using keras-2
