### ISSUE TITLE
Got error message when run examples cifar10_densenet.py

### ISSUE THREAD

**Issue by kemaswill** [farizrahman4u/keras-contrib#51]
I'm trying to fix the examples to fit keras-2, however I got the following error when I try to run the cifar10_densenet.py:

Traceback (most recent call last):
  File "examples/cifar10_densenet.py", line 38, in <module>
    input_shape=img_dim, weights=None)
  File "/home/ubuntu/Github/keras-contrib/keras_contrib/applications/densenet.py", line 117, in DenseNet
    dropout_rate, weight_decay)
  File "/home/ubuntu/Github/keras-contrib/keras_contrib/applications/densenet.py", line 487, in __create_dense_net
    dropout_rate=dropout_rate, weight_decay=weight_decay)
  File "/home/ubuntu/Github/keras-contrib/keras_contrib/applications/densenet.py", line 378, in __dense_block
    x = merge(x_list, mode='concat', concat_axis=concat_axis)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/layers.py", line 456, in merge
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/layers.py", line 117, in __init__
    self(input_tensors, mask=input_masks)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/layers.py", line 210, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1525, in concatenate
    return **tf.concat([to_dense(x) for x in tensors], axis)**
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1000, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Many guys have got the similar error when they call tf.concat(axis, [x1,x2,x3]) instead of tf.concat([x1,x2,x3], axis). However this is not the case here. Any one has any solution?

**Comment by ahundt** [comment]
@kemaswill I have a number of DenseNet Keras-2 patches in https://github.com/farizrahman4u/keras-contrib/pull/46

**Comment by ahundt** [comment]
@kemaswill I don't think it is fixed? I've updated both keras and keras-contrib to the latest version.

**Comment by kemaswill** [comment]
@ahundt Have you also update Tensorflow? What's your current version for keras and tensorflow?

**Comment by kemaswill** [comment]
@ahundt Mine is keras: 2.0.2, Tensorflow 1.0.1.
